### PR TITLE
Add ssh config file format to README

### PR DESCRIPTION
**Pull request by Salihan04**
For #18

### CODE REVIEW

**Comment by thepoppingone** [comment]
👍🏻👍🏻👍🏻

**Comment by thepoppingone** [comment]
👍🏻👍🏻👍🏻

**Comment by Salihan04** [comment]
@thepoppingone PR closed but not merged? 🤔

**Comment by thepoppingone** [comment]
Strange I can’t press merge from mobile phone lol

**Comment by Salihan04** [comment]
@thepoppingone Oh. U need to review and approve (in "Files changed" tab) first. Only then can merge. haha

**Comment by alvinsiew** [comment]
Nice! will be good if you include example of jump host and how use jump host on other host.

**Comment by alvinsiew** [comment]
> Nice! will be good if you include example of jump host and how use jump host on other host.

Can include the template without jump host as well. So more combinations of example.

README.md not upgraded with the new --init feature in usage example.

**Comment by Salihan04** [comment]
> > Nice! will be good if you include example of jump host and how use jump host on other host.
> 
> Can include the template without jump host as well. So more combinations of example.
> 
> README.md not upgraded with the new --init feature in usage example.

The --init feature will get the README after this PR is merged then I will pull from master branch for #28

**Review by alvinsiew — APPROVED** [review]

**Pull request merged**
